python train.py \
    --input_path /home/afukuchi/Codes/shinra-attribute-extraction/2020jp_tokenize_mecab_ipadic_bpe_tohoku_bert/JP-5/data1/ujiie/shinra/tohoku_bert/JP-5/City/ \
    --model_path /home/afukuchi/Codes/shinra-attribute-extraction/models/20210823_SAM/City/ \
    --lr 1e-5 \
    --bsz 8 \
    --epoch 5 \
    --grad_acc 1 \
    --grad_clip 1.0 \
    --optimizer SAM ;
echo "end city";
python train.py \
    --input_path /home/afukuchi/Codes/shinra-attribute-extraction/2020jp_tokenize_mecab_ipadic_bpe_tohoku_bert/JP-5/data1/ujiie/shinra/tohoku_bert/JP-5/Company/ \
    --model_path /home/afukuchi/Codes/shinra-attribute-extraction/models/20210823_SAM/Company/ \
    --lr 1e-5 \
    --bsz 8 \
    --epoch 5 \
    --grad_acc 1 \
    --grad_clip 1.0 \
    --optimizer SAM;
echo "end company"
